### ISSUE TITLE
running `npm install` or `learn` didn't actually install `json-server`

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/fewpjs-sending-data-with-fetch#10]
**Description**
The instructions in this lab say to run `npm install` or `learn` once to get `json-server` to install.  I did this and then when trying to run the next command in the instructions (`json-server --watch db.json`), bash gave me an error: 
`[16:22:49] (master) fewpjs-sending-data-with-fetch-online-web-ft-061019
// $ json-server --watch db.json
bash: json-server: command not found`

I ended up looking at the Readme of the json-server [github repo](https://github.com/typicode/json-server) and found the following command to manually installed it `npm install -g json-server`.  

I was then able to run the `json-server --watch db.json` successfully.  

**Expectation**
The lab would have worked by following the specified instructions 

**Actual Result**
Had to do some troubleshooting and install json-server manually then was able to continue with the lab.

**Comment by sgharms** [comment]
Good write up. Easy fix. Done!
