### ISSUE TITLE
Test Malfunction

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/fewpjs-sending-data-with-fetch#11]
Hi, I sat with AAQ trying to get these tests to pass. The right result is showing up in the DOM. The coaches said my code looked like the solutions and they hunted for any issues in the test but couldn't figure it out after an hour. Here are the errors that are continuing to show up.
submitData()
(node:5606) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    ✓ makes a POST request to /user with a name and email
{ id: 544, name: 'Steve', email: 'steve@steve.com' }
    1) handles the POST request response, retrieves the new id value and appends it to the DOM
{ id: 546, name: 'Sam', email: 'sam@sam.com' }
    2) handles a failed POST request using catch, appends the error message to the DOM

  1 passing (1s)
  2 failing

  1) submitData()
       handles the POST request response, retrieves the new id value and appends it to the DOM:
     AssertionError: expected '544' to include 546
      at Context.<anonymous> (test/indexTest.js:72:11)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) submitData()
       handles a failed POST request using catch, appends the error message to the DOM:
     AssertionError: expected '546' to include 'Unauthorized Access'
      at Context.<anonymous> (test/indexTest.js:89:11)

**Comment by sgharms** [comment]
I looked at your code. You have a critical bug. Look at your calls to `document.body`, are there any differences?

There's an implicit expectation that's not documented in the specification that I'll clarify, but make sure you return the `fetch`

**Comment by thistonyb** [comment]
Thanks for catching that innerHTML for me. I will try the return!
