### ISSUE TITLE
not sure that this .catch error example works

### ISSUE THREAD

**Issue by alouiscious** [learn-co-curriculum/fewpjs-sending-data-with-fetch#13]
I followed this labs instructions/example and could not replicate it.

<img width="955" alt="Screen Shot 2020-03-03 at 5 21 10 PM" src="https://user-images.githubusercontent.com/46434917/75835363-86a7fd80-5d73-11ea-8a3a-4ccf95287e48.png">
is a correction to this lab needed?

**Comment by lizbur10** [comment]
Hi there! I'm not sure why this wasn't working for you, but I'm unable to replicate the problem so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron School curriculum! 💙
