### ISSUE TITLE
README is unclear about where to write its example code, if at all

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/fewpjs-sending-data-with-fetch#14]
To begin, the **Analyze Data Sent in an HTML Form** section near the top says:

> We should expect that our "mini-browser," `fetch()` will need those same bits of information in order to send data to the server. Let's place this data inside our `form()` skeleton.

I'm not clear on what or where the `form()` skeleton is, unless it's referring to the `sample_form.html` file.

The lesson then has us build a `configurationObject` and use it to make a POST request with `fetch()` like this:

```
fetch("http://localhost:3000/dogs", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "Accept": "application/json"
  },
  body: JSON.stringify({
    dogName: "Byron",
    dogBreed: "Poodle"
  })
});
```
This is in the **Send the POST Request** section, halfway through the lesson. I had assumed that we were supposed to write this in the `index.js` file, but the README doesn't say. But here's what it _does_ say (in the same section as the code above):

> With the JSON server running, if you open up `sample_form.html` or `index.html`, you can use the above to successfully send a POST request and persist data to `db.json`.

If I write that `fetch()` code in the `index.js` file, then opening `index.html` makes a POST request with that code. However, opening `sample_form.html` does _not_; instead, it makes a POST request with its HTML form (which I think it's supposed to do).

Further down in that section, the README also says this:

> **Note:** As a security precaution, most modern websites block the ability to use `fetch()` in console while on their website, so if you are testing out code in browser, make sure to be on a page like `index.html` or `sample_form.html`.

Does that mean that we were supposed to write out that `fetch()` code in the DevTools console, and _not_ in the `index.js` file? If that's the case, **do _NOT_ try this on the `sample_form.html` page!** As I discovered, that seemed to cause http://localhost:3000 to freeze (i.e. take forever to load) for whatever reason, even after stopping `json-server`, and I had to re-clone the lab. However, it worked OK with the console in the `index.html` file.

All of this is before the actual "lab" part itself. I'm just not clear on where or if we were supposed to write that `fetch()` code above.

Thanks a lot for looking into this!

--- Sdcrouse

**Comment by Sdcrouse** [comment]
Update: The reason that http://localhost:3000 freezes on the `sample_form.html` page, appears to be because at that part of the lesson/lab, the call to `fetch()` is written without any calls to `then()`. It looks like this: 
```
fetch("http://localhost:3000/dogs", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "Accept": "application/json"
  },
  body: JSON.stringify({
    dogName: "Byron",
    dogBreed: "Poodle"
  })
});
```
My guess is that the program freezes because there's nothing to handle the response. When I add calls to `then()`: 
```
fetch("http://localhost:3000/dogs", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "Accept": "application/json"
  },
  body: JSON.stringify({
    dogName: "Byron",
    dogBreed: "Poodle"
  })
})
  .then(function(response) {
    return response.json();
  })
  .then(function(object) {
    console.log(object);
  });
```
Then the code works just fine in the DeveloperTools console on the `sample_form.html` page; nothing freezes.

**Comment by lizbur10** [comment]
Hi @Sdcrouse ! Thanks for spotting these issues and submitting feedback! I was not able to replicate the issue with the page freezing, so I did not make any changes for that. However, the README has been updated to clarify the other points of confusion you identified. 

Thanks for contributing to the Flatiron School curriculum! 💙
