### ISSUE TITLE
json-server: command not found when running json-server --watch db.json

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/fewpjs-sending-data-with-fetch#16]
To fix this, and have it run, you must type the local path:

$ ./node_modules/.bin/json-server --watch db.json or..
$ npx json-server --watch db.json

**Comment by lizbur10** [comment]
Hi there! I'm not sure why this wasn't working for you, but I'm unable to replicate the problem so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron School curriculum! 💙
