### ISSUE TITLE
errors running npm install -g json-server

### ISSUE THREAD

**Issue by rohanphillips** [learn-co-curriculum/fewpjs-sending-data-with-fetch#19]
when running  npm install -g json-server

the following errors were received

`npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trader/.npm/_logs/2020-10-08T12_46_45_969Z-debug.log`

After much agony, found that running sudo npm install -g json-server gets the job done.  Please add this help to the page so other users don't waste hours like I just did.  A Unix newb :)

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. We have updated the lesson to address the issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing to the Flatiron School curriculum! 💙
