### ISSUE TITLE
Submit key value pair

### ISSUE THREAD

**Issue by baker615512** [learn-co-curriculum/fewpjs-sending-data-with-fetch#20]
Because there is a name="submit" in the sample form, it is creating a key value pair of submit: "Submit" when an input is submitted.

`<form action="http://localhost:3000/dogs" method="POST">
  <label> Dog Name: <input type="text" name="dogName" id="dogName" /></label><br />
  <label> Dog Breed: <input type="text" name="dogBreed" id="dogBreed" /></label><br />
  <input type="submit" name="submit" id="submit" value="Submit" />
</form>`

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this and submitting an issue! The materials have been updated to fix the error.

Thanks for contributing to the Flatiron School curriculum 💙
