### ISSUE TITLE
Instructions typo, write a method

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/fewpjs-sending-data-with-fetch#22]
Line 400 of Readme says 
``index.js`, write a method, `submitData`, that takes two strings arguments, one`

Should be "write a function" instead

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this and submitting an issue! The materials have been updated to fix the error.

Thanks for contributing to the Flatiron School curriculum 💙
