### ISSUE TITLE
Update to body text - word replacement

### ISSUE THREAD

**Issue by gracet37** [learn-co-curriculum/fewpjs-sending-data-with-fetch#6]
Last paragraph in this README - should be "Simple Liker" not "Simple Looker"
Last paragraph:
"With this we're ready to to stitch server updates (reads and updates) with DOM updating and event handling. We're almost ready to build the "Simple Looker" from scratch!"

**Comment by sgharms** [comment]
Thanks @gracet37 . Fixed!
